apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metal3
resources:
- namespace.yaml
- service_account.yaml
- role.yaml
- role_binding.yaml
- crds/metal3.io_baremetalhosts_crd.yaml
- operator_ironic.yaml
configMapGenerator:
- envs:
  - ironic_bmo_configmap.env
  name: ironic-bmo-configmap
secretGenerator:
- literals:
  - password=changeme
  name: mariadb-password
  type: Opaque
