apiVersion: install.example.com/v1alpha1
kind: Install
metadata:
  name: example-install
spec:
  # Add fields here
  targetNamespace: operator-sample
  setowner: true
  registry: 
    override:
      baremetal-operator: vincentpli/baremetal-operator:v0.1